"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_controller_1 = require("../controllers/user.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const user_validator_1 = require("../validators/user.validator");
const router = (0, express_1.Router)();
router.route("/register").post((0, user_validator_1.userRegisterValidator)(), user_controller_1.registerUser);
router.route("/login").post((0, user_validator_1.userLoginValidator)(), user_controller_1.loginUser);
router.route("/refresh-token").post(user_controller_1.refreshAccessToken);
router.route("/logout").post(auth_middleware_1.verifyJWT, user_controller_1.logoutUser);
exports.default = router;
